[build]
  functions = ".netlify/functions"
  publish = "."
  
[build.environment]
  NODE_VERSION = "18"

# Include templates directory in the build
[build.processing]
  skip_processing = false

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Make sure templates directory is included
[build.ignore]
  # Don't ignore anything important
